### ISSUE TITLE
Using Gemini pro 1.5 exp with openrouter often leads to error

### ISSUE THREAD

**Issue by provencher** [kevinhermawan/swift-llm-chat-openai#5] opened 2024-10-14 18:02 UTC
"Error sending message: keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))"

It seems like if id is missing from the return packet, the whole message sends. It happens very often with gemeni pro 1.5, not so much with other models.

**Comment by kevinhermawan** [comment] 2024-10-14 19:43
Oh, I’m going to check it right now! Thanks!

**Comment by kevinhermawan** [comment] 2024-10-14 21:06
I’m getting a 200 status code, but the response is an error message. 😕

```json
{
  "error": {
    "message": "{\n  \"error\": {\n    \"code\": 429,\n    \"message\": \"Resource has been exhausted (e.g. check quota).\",\n    \"status\": \"RESOURCE_EXHAUSTED\"\n  }\n}\n",
    "code": 429
  }
}
```

I’ll keep this for now since the issue is from the provider.

**Comment by kevinhermawan** [comment] 2024-10-14 21:20
Check out this discussion: https://x.com/kvnhermawan/status/1845933671100068168

For now, as I’ve mentioned before, I won’t make any changes. It would complicate the code unnecessarily for a specific issue.

**Comment by provencher** [comment] 2024-10-15 01:46
No worries - good to know it's a rate limit problem.

**Comment by provencher** [comment] 2024-10-18 21:00
Actually the issue with this error is the error message. I saw it using Claude sonnet 3.5 today as well.

It would be very good if you had a more graceful error message for rate limiting. Having a decoding error is very hard to handle for an app using this library.

**Comment by kevinhermawan** [comment] 2024-10-18 22:53
Yup, I’m working on improving error handling.

However, for this particular issue, I’ve created a specific pull request (#9) to address the fallback model when using OpenRouter. Hope it helps!

**Comment by kevinhermawan** [comment] 2024-10-26 22:52
I’ve improved the error handling in [1.1.2](https://github.com/kevinhermawan/swift-llm-chat-openai/releases/tag/1.1.2). I think it solved this issue, so I’ll close this issue.

**Closed as completed by kevinhermawan** 2024-10-26 22:52 UTC

**Comment by provencher** [comment] 2024-10-28 11:37
I updated last after you posted this and the error came up again today.

**Comment by provencher** [comment] 2024-10-28 11:39
I looked through your code and you're still not catching cases where the json decoding fails, at least for I can see.

**Comment by kevinhermawan** [comment] 2024-10-28 21:29
Yes, more error handlers will be released in the upcoming release, including those for decoding failures.
