### ISSUE TITLE
Server error trying to use Gemini api 

### ISSUE THREAD

**Issue by provencher** [kevinhermawan/swift-llm-chat-openai#18] opened 2024-11-10 01:02 UTC
I’m trying to use the new ChatGPT api support for Gemini and I’m getting a server error.

https://ai.google.dev/gemini-api/docs/openai

**Comment by kevinhermawan** [comment] 2024-11-12 10:07
Wow, thanks for the info. was totally unaware that Google has an OpenAI compatibility API. 😂

**Comment by provencher** [comment] 2024-11-12 12:01
Yeah it just came out last Friday - very new stuff

**Comment by kevinhermawan** [comment] 2024-11-12 13:08
Hi @provencher, the issue is that Gemini doesn’t provide the `id` in the completion response. I’ve merged PR #19 to fix this. It works for me. Could you please confirm by checking the main branch before I release a new version?

**Comment by provencher** [comment] 2024-11-12 15:03
Hey yep got this working, thanks!

**Closed as completed** 2024-11-12 15:03 UTC
